using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Rigidbody))]
[RequireComponent(typeof(SphereCollider))]
[RequireComponent(typeof(Animator))]
// ЧиДч НКХЉИГЦЎИІ УпАЁЧб АдРг ПРКъСЇЦЎПЁ ЧЪПфЧб ФФЦїГЭЦЎАЁ ОјДйИщ РкЕПРИЗЮ УпАЁЧбДй.
// (Rigidbody, SphereCollider, Animator)

public class EnemyMovement : MonoBehaviour
{
    public float pursuitSpeed;
    public float wanderSpeed; // ЦђЛѓНУ МгЕЕ
    public float currentSpeed; // ЧіРч МгЕЕ

    public float directionChangeInterval; // ЙшШИЧв ЙцЧтРЧ РќШЏ КѓЕЕ
    public bool followPlayer; // ЧУЗЙРЬОю УпРћ БтДЩ (offНУ ЙшШИИИ)

    Coroutine moveCoroutine; // ЧіРч НЧЧрСпРЮ РЬЕП ФкЗчЦО ТќСЖИІ РњРх (РћРЛ ИёРћСіЗЮ ПХБш)
    SphereCollider sphereCollider; 
    Rigidbody rigidbody;
    Animator animator;

    Transform targetTransform = null; // ЧУЗЙРЬОюИІ УпРћЧв ЖЇ ЛчПы (PlayerObjectРЧ transformРЛ ОђОю targetTransformПЁ ДыРд)
    Vector3 endPosition; // ЙшШИЧЯДТ ФГИЏХЭРЧ ИёРћСі
    float currenAngle = 0; // ЙшШИЧв ЙцЧтРЛ ЙйВм АцПь БтСИ АЂЕЕПЁ ЛѕЗЮПю АЂЕЕ ДѕЧиСм

    void Start()
    {
        animator = GetComponent<Animator>();
        rigidbody = GetComponent<Rigidbody>();
        sphereCollider = GetComponent<SphereCollider>();
        currentSpeed = wanderSpeed;
        StartCoroutine(WanderRoutine());
        // currentSpeedПЁ wanderSpeedИІ ЧіРч МгЕЕЗЮ РњРх, УГРНПЁДТ ЙшШИЧЯДТ МгЕЕЗЮ РћРЬ УЕУЕШї ПђСїРЬЕЕЗЯ
    }

    void Update()
    {
        Debug.DrawLine(rigidbody.position, endPosition, Color.red);
    }

    public IEnumerator WanderRoutine()
    {
        while (true)
        {
            ChooseNewEndPoint(); // ЛѕЗЮПю ИёРћСіИІ МБХУЧд

            if(moveCoroutine != null) // nullРЮСі ОЦДбСіИІ ШЎРЮЧи РћРЧ РЬЕППЉКЮ УМХЉ (nullРЬ ОЦДЯЖѓИщ РЬЕП Сп)
            {
                StopCoroutine(moveCoroutine);
            }
            moveCoroutine = StartCoroutine(Move(rigidbody, currentSpeed));
        }
    }

    void ChooseNewEndPoint()
    {
        currenAngle += Random.Range(0, 360); // 0~360 ЛчРЬ АЊ ЙЋРлРЇ МБХУ -> currentAngleАЊАњ ЙЋРлРЇ АЊ ДѕЧд -> ЛѕЗЮПю ЙцЧт ГЊХИГЛДТ АЂЕЕ
        currenAngle = Mathf.Repeat(currenAngle, 360); // СжОюСј АЊРЬ СіСЄЧб АЊРЧ ЙќРЇ ОШПЁ Ещ ЖЇБюСі ЙнКЙ (360КИДй РлАХГЊ ХЌ Мі ОјДй)
        endPosition += Vector3FromAngle(currenAngle); // АсАњ АЊРЛ endposition АЊПЁ ДѕЧЯАэ ДыРд
    }

    Vector3 Vector3FromAngle(float inputAngleDegrees)
    {
        float inputAngleRadius = inputAngleDegrees * Mathf.Deg2Rad;
        return new Vector3(Mathf.Cos(inputAngleRadius), Mathf.Sin(inputAngleRadius), 0);
        // РдЗТЙоРК inputAngleDegrees АЊПЁ Mathf.Deg2Rad ЛѓМіИІ АіЧи КЏШЏ
        //КЏШЏЧб АЊРЛ ЛчПыЧи РћРЧ ЙцЧтРИЗЮ ЛчПыЧв Vector Л§МК
    }

    public IEnumerator Move(Rigidbody rigidBodyToMove, float speed)
    {
        float remainingDistance = (transform.position - endPosition).sqrMagnitude;
        while(remainingDistance > float.Epsilon)
        {
            if(targetTransform != null)
            {
                endPosition = targetTransform.position;
            }
            if(rigidBodyToMove != null)
            {
                animator.SetBool("isWalking", true);
                Vector3 newPosition = Vector3.MoveTowards(rigidBodyToMove.position, endPosition, speed * Time.deltaTime);

                rigidbody.MovePosition(newPosition);
                remainingDistance = (transform.position - endPosition).sqrMagnitude;
            }

            yield return new WaitForFixedUpdate();
        }
        animator.SetBool("isWalking", false);
    }

    private void OnTriggerEnter(Collision collision)
    {
        if(collision.gameObject.CompareTag("Player") && followPlayer)
        {
            currentSpeed = pursuitSpeed;
            targetTransform = collision.gameObject.transform;
            if(moveCoroutine != null)
            {
                StopCoroutine(moveCoroutine);
            }
            moveCoroutine = StartCoroutine(Move(rigidbody, currentSpeed));
        }
    }

    void OnTriggerExit(Collider collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            animator.SetBool("isWalking", false);
            currentSpeed = wanderSpeed;

            if(moveCoroutine != null)
            {
                StopCoroutine(moveCoroutine);
            }
            targetTransform = null;
        }
    }

    void OnDrawGizmos()
    {
        if(sphereCollider != null)
        {
            Gizmos.DrawWireSphere(transform.position, sphereCollider.radius);
        }
    }
}


// https://my-develop-note.tistory.com/35